name: Deploy React App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to Hostinger via FTP
      run: |
        # Install lftp
        sudo apt-get update && sudo apt-get install -y lftp
        
        # Deploy using hardcoded FTP credentials
        lftp -e "
          set ssl:verify-certificate no;
          open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' ${{ secrets.FTP_HOST }};
          mirror -R ./build /public_html;
          bye
        "
