name: Deploy React App to Hostinger

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Specify your Node.js version here

    - name: Install dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build

    - name: Deploy to Hostinger via FTP
      run: |
        curl -LO https://github.com/oleksandr/ftp-deploy/releases/download/v1.0.0/ftp-deploy-linux-x64.tar.gz
        tar -xvf ftp-deploy-linux-x64.tar.gz
        ./ftp-deploy -h ${{ secrets.HOSTINGER_FTP_HOST }} \
                     -u ${{ secrets.HOSTINGER_FTP_USER }} \
                     -p ${{ secrets.HOSTINGER_FTP_PASSWORD }} \
                     -r ${{ secrets.HOSTINGER_FTP_REMOTE_PATH }} \
                     -l ./build
